using Tyuiu.ShakhovDK.Sprint2.Task5.V10.Lib;
DataService ds = new DataService();
int g, m, n;
string res;
Console.Title = "Спринт #2 | Выполнил: Шахов Д.К | ИИПБ-24-2";
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* Спринт #2                                                                              *");
Console.WriteLine("* Тема: Оператор switch                                                                  *");
Console.WriteLine("* Задание #5                                                                             *");
Console.WriteLine("* Вариант #10                                                                            *");
Console.WriteLine("* Выполнил: Шахов Даниил Константинович | ИИПБ-24-2                                      *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                               *");
Console.WriteLine("* Дата некоторого дня характеризуется тремя натуральными числами:\n" +
"g (год), m (порядковый номер месяца) и n (число).\n" +
"По заданным g, n и m определить дату предыдущего дня. Заданный год не является високосным*");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                                       *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* Введите год:                                                                           *");
g = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("* Введите месяц:                                                                         *");
m = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("* Введите число:                                                                         *");
n = Convert.ToInt32(Console.ReadLine());
res = ds.FindDateOfPreviousDay(g, m, n);
Console.WriteLine("******************************************************************************************");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                                             *");
Console.WriteLine($"Дата предыдущего дня = {res}");
Console.WriteLine("******************************************************************************************");
Console.ReadKey();